### ISSUE TITLE
Record Caching

### ISSUE THREAD

**Issue by jayfunk** [jayfunk/pocketguide-web-server#1]
Need to build out the caching of the event records once fetched from the sheet. That way we wont have to worry about reaching usage limits and changes wont be often enough to warrant always fetching the latest. The cached result should also have a timestamp of when it was stored that way the client can verify if the version it has locally is out of date or not.

**Comment by ahutchings** [comment]
Done in 83f2148e1221abc3c12dcacc0ccd54066b71eda5 and c99a4ebaf439498babed88028e5f0221372f0ca5. I configured the default cache expiry to 12 hours. When a request comes into the server, it will first try to fetch from memcached, falling back to Google.

**Comment by jayfunk** [comment]
Awesome! Thanks Andrew!
