### ISSUE TITLE
New File ID

### ISSUE THREAD

**Issue by jayfunk** [jayfunk/pocketguide-web-server#3]
I was trying to switch to a new file but it appears the google API cannot find the file ID. I pulled the id from the google doc url. Is that where it is supposed to come from?

**Comment by ahutchings** [comment]
I think that's where I got it from for the original file. You could try [listing the files](https://github.com/google/google-api-nodejs-client/blob/6bd1f3451333b144d53e380e35c2616ddba977a7/apis/drive/v2.js#L988) to verify the ID.

Is the file available with the same user account/oauth token? Google might be returning a 404 if the file is not accessible with the given credentials.

**Comment by jayfunk** [comment]
Fixed it. The service email that is configured for the web server did not have permissions to the new file.
